import type { Metadata } from "next";
import { Dosis, Catamaran } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import Footer from "./footer";
import { prod } from "../config";
// import Head from "next/head";

//stylesheet
import "../../public/assets/img/favicon.png";
import "../../public/assets/css/bootstrap.min.css";
import "../../public/assets/css/animate.min.css";
import "../../public/assets/css/flaticon.css";
import "../../public/assets/css/fontawesome.min.css";
import "../../public/assets/css/bootstrap-icons.css";
import "../../public/assets/css/meanmenu.css";
import "../../public/assets/css/magnific-popup.min.css";
import "../../public/assets/css/swiper.min.css";
import "../../public/assets/css/owl.carousel.min.css";
import "../../public/assets/css/style.css";
import "../../public/assets/css/responsive.css";
import Script from "next/script";

const dosis = Dosis({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

const catamaran = Catamaran({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dosis.className} ${catamaran.className}`}>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        <Script src="HelpYourSolution/assets/js/jquery.min.js"></Script>
        <Script src="HelpYourSolution/assets/js/popper.min.js"></Script>
        <Script src="HelpYourSolution/assets/js/bootstrap.bundle.min.js"></Script>
        <Script src="HelpYourSolution/assets/js/jquery.meanmenu.js"></Script>
        <Script src="HelpYourSolution/assets/js/jquery.appear.min.js"></Script>
        <Script src="HelpYourSolution/assets/js/jquery.waypoints.min.js"></Script>
        <Script src="HelpYourSolution/assets/js/jquery.counterup.min.js"></Script>
        <Script src="HelpYourSolution/assets/js/owl.carousel.min.js"></Script>
        <Script src="HelpYourSolution/assets/js/jquery.magnific-popup.min.js"></Script>
        <Script src="HelpYourSolution/assets/js/isotope.pkgd.min.js"></Script>
        <Script src="HelpYourSolution/assets/js/swiper.min.js"></Script>
        <Script src="HelpYourSolution/assets/js/wow.min.js"></Script>
        <Script src="HelpYourSolution/assets/js/main.js"></Script>
      </body>
    </html>
  );
}
